version: "3.7"
services:
  redis:
    image: redis:latest
    container_name: go-redis-play-redis
    volumes:
      - redis-data:/data
    restart: always
    ports:
      - "6379:6379"
volumes:
  redis-data:
    driver: local
